USE [master]
GO

/****** Object:  Database [myprojects]    Script Date: 20.04.2015 16:23:48 ******/
CREATE DATABASE [myprojects] ON  PRIMARY 
( NAME = N'myprojects', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\myprojects.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'myprojects_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\myprojects_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [myprojects] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [myprojects].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [myprojects] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [myprojects] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [myprojects] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [myprojects] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [myprojects] SET ARITHABORT OFF 
GO

ALTER DATABASE [myprojects] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [myprojects] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [myprojects] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [myprojects] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [myprojects] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [myprojects] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [myprojects] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [myprojects] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [myprojects] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [myprojects] SET  DISABLE_BROKER 
GO

ALTER DATABASE [myprojects] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [myprojects] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [myprojects] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [myprojects] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [myprojects] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [myprojects] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [myprojects] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [myprojects] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [myprojects] SET  MULTI_USER 
GO

ALTER DATABASE [myprojects] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [myprojects] SET DB_CHAINING OFF 
GO

ALTER DATABASE [myprojects] SET  READ_WRITE 
GO


